version: "3.8"

services:
  db:
    image: postgres:15
    container_name: cinemio_db
    environment:
      POSTGRES_DB: cinemio
      POSTGRES_USER: ci_user
      POSTGRES_PASSWORD: ci_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d  # inicializa o DB Keycloak automaticamente

  minio:
    image: minio/minio
    container_name: cinemio_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # Painel de administração
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: cinemio_keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: ci_user
      KC_DB_PASSWORD: ci_pass
      KC_BOOTSTRAP_ADMIN_USERNAME: animio
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8005:8080"  # mapeia porta 8080 do container para 8005 na máquina
    depends_on:
      - db
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  db_data:
  minio_data:
  keycloak_data:
