version: "3.8"

services:
  db:
    image: postgres:15
    container_name: cinemio_db
    environment:
      POSTGRES_DB: cinemio
      POSTGRES_USER: ci_user
      POSTGRES_PASSWORD: ci_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: cinemio_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # Painel de administração
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data

volumes:
  db_data:
  minio_data:
