version: "3.8"

services:
  # Serviço da sua aplicação CodeIgniter
  app:
    build: .
    container_name: cinemio_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    # ESTA É A ALTERAÇÃO:
    # Este comando é executado toda vez que o contêiner inicia.
    # 1. Ajusta as permissões da pasta 'writable'.
    # 2. Inicia o servidor Apache em primeiro plano.
    command: >
      bash -c "chmod -R 777 /var/www/html/writable && apache2-foreground"

  db:
    image: postgres:15
    container_name: cinemio_db
    environment:
      POSTGRES_DB: cinemio
      POSTGRES_USER: ci_user
      POSTGRES_PASSWORD: ci_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  minio:
    image: minio/minio
    container_name: cinemio_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: cinemio_keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: ci_user
      KC_DB_PASSWORD: ci_pass
      KC_BOOTSTRAP_ADMIN_USERNAME: animio
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"        # opcional em dev
      KC_HOSTNAME: http://localhost:8005
    command: start-dev --hostname http://localhost:8005
    ports:
      - "8005:8080"
    depends_on:
      - db
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak-theme:/opt/keycloak/themes



volumes:
  db_data:
  minio_data:
  keycloak_data:
